name: Deploy to Argo Workflows

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up GKE cluster
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.GCP_REGION }} --project ${{secrets.GCP_PROJECT}}
      env:
      GCP_REGION: us-central1
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
    - name: Deploy workflows to Argo Workflows
      run: |
        for file in ../../../argo-workflows/*.yaml; do
          argo submit -n argo "$file" --watch
        done
