name: Deploy to Argo Workflows

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install Argo CLI
      run: |
        curl -sLO https://github.com/argoproj/argo-workflows/releases/latest/download/argo-linux-amd64.gz
        gunzip argo-linux-amd64.gz
        chmod +x argo-linux-amd64
        sudo mv argo-linux-amd64 /usr/local/bin/argo
        argo version

    - name: Set up GKE cluster
      run: |
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region us-central1 --project ${{secrets.GCP_PROJECT}}
    - name: Deploy workflows to Argo Workflows
      run: |
        for file in ./argo-workflows/*.yaml; do
          argo submit -n argo "$file" --watch
        done
